### ISSUE TITLE
Clean UP & Dockerization eos2rd8

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2rd8#2] opened 2023-06-30 16:53 UTC

**Comment by simrantan** [comment] 2023-06-30 19:13
The workflow is failing to upload this code to dockerhub - when looking into the issue, I saw this error: `Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.305.0/_diag/Worker_20230630-160159-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)`

Just to check - this is a remote device, right? Not my device(I am currently dealing with a space issue on my laptop and how its broken ubuntu at the moment so I'm unsure if it's my laptop's fault). Also, it seems like this might not be an issue with the code itself.

**Comment by GemmaTuron** [comment] 2023-07-01 07:32
Hi @simrantan 
As @ZakiaYahya shared the other day in the meeting, the Git Actions runners have a cap of 10 GB (or 7GB?) size. She is working on a solution [here](https://github.com/ersilia-os/eos44zp/pull/6) - if that works we could apply it to this model as well

**Comment by GemmaTuron** [comment] 2023-07-01 07:33
but menawhile @simrantan you can fork the model and work on reformatting it to the latest eos template format

**Comment by GemmaTuron** [comment] 2023-07-05 13:25
@simrantan 
the model upload to dockerhub is failing, please check it

**Comment by simrantan** [comment] 2023-07-05 17:53
It appears to be the same issue as before - `System.IO.IOException: No space left on device `
Should I look into ways to reduce the size of the model? I will also ask in the slack if anyone has made progress in resolving this issue with large models.

**Comment by GemmaTuron** [comment] 2023-07-06 05:37
Hi @simrantan 

If you recall, in the last meeting Zakia explained she had not been able to allocate more swap space to the runner, and we decided to split the model in three to save space.
In this case, there are no checkpoints so is just the packages installed that are too large? Is there anything not needed in the repo that could be optimized?

**Comment by simrantan** [comment] 2023-07-07 06:17
Thank you for all the advice! I have begun understanding how to cache files per the model in the internship project thread and working on my fork to see what files can be cached.

**Comment by simrantan** [comment] 2023-07-08 01:42
@GemmaTuron I have spent most of today implementing caching on this model and I think I have finally found a configuration that works (tested locally to make sure the model itself hasn't been impacted). Should I submit a PR request to test the if the caching worked?
Also, while looking into this issue I saw the repo itself is not actually that large (1.22 KB) so it seems like the dependencies/packages being installed may be what causes the size to be too much for github actions. In an effort to reduce the number of unnecessary packages, can I delete the git-lfs install for this model since it does not track any large files in checkpoints or elsewhere  (have already gotten rid of gitattributes because of this)?

**Comment by GemmaTuron** [comment] 2023-07-10 08:37
@simrantan the model test has failed, please check

**Comment by simrantan** [comment] 2023-07-10 21:08
@GemmaTuron 
It appears that Riley has received the exact same error as I am now receiving on this model(copied below). I initially thought this error may be a result of the editing I did to the workflow files, since the model merged perfectly fine before and that is the only change I have made to the model since the last merge. However,  this error occurs in the metadata-to-airtable file which is unrelated to the file I edited, and Riley, who has not touched any workflow files, is recieving word for word the same issue (and our models were merged at the exact same time), which means it might not be related to the changes I made. 

A detailed reading of the error log and research online says that the issue is resulting from an invalid JSON input (either empty input or invalid formatting). Since this error is triggered by the line `rm = RepoMetadataFile(model_id=repo_name, config_json=None)`, it could be that the repo_name is an invalid input? Or that the 'fh' file being loaded into obj_dict is invalid, since that is what fails to be decoded. 

**Error:** 
`Traceback (most recent call last):
  File "/home/runner/work/eos2rd8/eos2rd8/update_metadata_to_airtable.py", line 13, in <module>
    rm = RepoMetadataFile(model_id=repo_name, config_json=None)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/hub/content/card.py", line 401, in __init__
    ErsiliaBase.__init__(self, config_json=config_json, credentials_json=None)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/core/base.py", line [27](https://github.com/ersilia-os/eos2rd8/actions/runs/5505856558/jobs/10033761616#step:7:28), in __init__
    self.cfg = Config(json_file=config_json)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/utils/config.py", line 161, in __init__
    eval_obj_dict = _eval_obj(json_file)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/utils/config.py", line 132, in _eval_obj
    obj_dict = json.load(fh)
  File "/usr/share/miniconda/lib/python3.10/json/__init__.py", line [29](https://github.com/ersilia-os/eos2rd8/actions/runs/5505856558/jobs/10033761616#step:7:30)3, in load
    return loads(fp.read(),
  File "/usr/share/miniconda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/share/miniconda/lib/python3.10/json/decoder.py", line [33](https://github.com/ersilia-os/eos2rd8/actions/runs/5505856558/jobs/10033761616#step:7:34)7, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/share/miniconda/lib/python3.10/json/decoder.py", line [35](https://github.com/ersilia-os/eos2rd8/actions/runs/5505856558/jobs/10033761616#step:7:36)5, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by GemmaTuron** [comment] 2023-07-11 09:49
@simrantan 

The cached dependencies is not working, could you please share here what did you try? which are the pieces of  code you added to the docker build workflow?

**Comment by simrantan** [comment] 2023-07-12 05:03
Yes absolutely! 
I added these two steps to the docker workflow: 
` - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ runner.workspace }}/.conda
            ${{ runner.workspace }}/ersilia
            ${{ runner.workspace }}/.cache/pip
          key: ${{ runner.os }}-conda-pip-${{ github.sha }}
    
      - name: Cache Docker image
        id: cache-docker-image
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.event.repository.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ github.event.repository.name }}-`
These two steps should cache installed dependencies and the image.

**Comment by GemmaTuron** [comment] 2023-07-12 07:32
Can you have a look at the actions and try to identify how we could modify these so that it does not fail?

**Comment by simrantan** [comment] 2023-07-12 18:55
Yes for sure I have been looking at the error and online for similar issues and will update when I have a more solid understanding of what might have gone wrong! @miquelduranfrigola is also planning a meeting wit Zakia and I about these dockerhub upload issues and discusse going over this model in more depth together.

**Comment by simrantan** [comment] 2023-07-13 01:32
I have looked into this issue and found that it is actually that there is still not enough space left on device: 

#8 7333.8 👍 Model eos2rd8 fetched successfully!
#8 DONE 7337.7s

#10 exporting to image
#10 exporting layers
#10 exporting layers 649.7s done
#10 ERROR: mount callback failed on /tmp/containerd-mount621917944: mount callback failed on /tmp/containerd-mount1087500232: failed to write compressed diff: failed to create diff tar stream: failed to copy: write /var/lib/buildkit/runc-overlayfs/content/ingest/3f9a59ca5c765fd76689356ac05f98c20fead8ef74bd94918f67cf099b8d0119/data: no space left on device
------
 > exporting to image:
------
ERROR: failed to solve: mount callback failed on /tmp/containerd-mount621917944: mount callback failed on /tmp/containerd-mount1087500232: failed to write compressed diff: failed to create diff tar stream: failed to copy: write /var/lib/buildkit/runc-overlayfs/content/ingest/3f9a59ca5c765fd76689356ac05f98c20fead8ef74bd94918f67cf099b8d0119/data: no space left on device
Error: buildx failed with: ERROR: failed to solve: mount callback failed on /tmp/containerd-mount621917944: mount callback failed on /tmp/containerd-mount1087500232: failed to write compressed diff: failed to create diff tar stream: failed to copy: write /var/lib/buildkit/runc-overlayfs/content/ingest/3f9a59ca5c765fd76689356ac05f98c20fead8ef74bd94918f67cf099b8d0119/data: no space left on device

We can see that in this version, the model is fetched successfully, but fails to export to image because there isn't enough space in docker. I may need to see if there are more files that can be cached. I am also going to discuss with Miquel about building images locally and this model in general to see if there are alternate solutions to caching that can be applied to all overly large models.

**Comment by GemmaTuron** [comment] 2023-07-13 06:31
I don't understand why this model is using up so much space..
Let's add it to the list of things to discuss today

**Comment by GemmaTuron** [comment] 2023-07-25 07:00
A note on this
@simrantan is working on creating a Docker container from local to bypass the limit of git actions. This will also apply to `eos44zp `with @ZakiaYahya once completed.
Please add documentation to the process so we can improve the gitbook.

**Closed as completed** 2023-08-24 10:45 UTC
